global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: product-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8083"]

  - job_name: inventory-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8084"]

  - job_name: cart-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8085"]

  - job_name: order-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8086"]

  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8087"]

  - job_name: search-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8089"]

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8090"]
